name: Build and push to ECR

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4.0.0

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: $ {{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: $ {{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $ {{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag and push image
        env:
          ECR_REGISTRY: $ {{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: task-tracker-api
          IMAGE_TAG: latest
        run:  |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
